import { Poppins, Roboto_Serif } from "next/font/google";
import "./globals.css";

export const robotoSerif = Roboto_Serif({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-robotoSerif",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Crunch Affair",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoSerif.className + " " + "bg-zinc-100"}>
        {children}
      </body>
    </html>
  );
}
